### ISSUE TITLE
SQLSTATE[42000]

### ISSUE THREAD

**Issue by kai1083** [magento-hackathon/Hackathon_MultistoreBlocks#10]
Any idea what says the error message?

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1, query was: DELETE FROM `cms_block_store` WHERE (block_id in())

**Comment by peterjaap** [comment]
This is fixed with https://github.com/magento-hackathon/Hackathon_MultistoreBlocks/commit/7c4aff14003b9d524a9c1f4e963e743c444d2819
