### ISSUE TITLE
Different Titles Per Language

### ISSUE THREAD

**Issue by sprankhub** [magento-hackathon/Hackathon_MultistoreBlocks#12]
Thanks for this awesome extension!

Magento normally allows to have different block titles per language. This perfectly makes sense to me since you can use the language-specific title in your template. Unfortunately, the multistore extension breaks this functionality and only allows one title for all store views. Is there any reason for it?

**Comment by JeroenBoersma** [comment]
Hi Simon, here is my follow-up. In general, titles for these blocks are not used anywhere except the admin to recognize them. I cannot imagine whenever I used them before, there are just "admin labels" to look them up.

This is the main reason why the arent' split into separate fields.

**Comment by sprankhub** [comment]
Hmm... I personally heavily use translated titles in my templates. And since Magento by default allows translated titles, I think this extension should do that, too.
Would you merge a PR providing the possibility to translate the titles?

**Comment by peterjaap** [comment]
I've also never personally used those titles for anything other than recognising the blocks in the admin, but sure :)

**Comment by JeroenBoersma** [comment]
:100: for supporting both ;)

**Comment by sprankhub** [comment]
Awesome, working on it :)
