### ISSUE TITLE
UI for multi language in block edit mode

### ISSUE THREAD

**Issue by peterjaap** [magento-hackathon/Hackathon_MultistoreBlocks#3]

**Comment by peterjaap** [comment]
What is the idea behind this ticket? The description is a little bit too vague.

**Comment by wigman** [comment]
putting all available translations of a block together in one static block edit page. We kinda succeeded in this at the hackathon, but I think it wasn't entirely completed.

**Comment by peterjaap** [comment]
I think we did finish it. Could you check the latest version and see whether that's what you expected?
