### ISSUE TITLE
Add copy of a block

### ISSUE THREAD

**Issue by JeroenBoersma** [magento-hackathon/Hackathon_MultistoreBlocks#9]

**Comment by wigman** [comment]
Dit is eigenlijk de belangrijkste feature die we nog missen. Ben jij daar dus mee bezig of van plan dit nog te implementeren?

**Comment by JeroenBoersma** [comment]
Ik probeer het eraan klussen tot de vrijdagen te beperken... Als je zin hebt mag je het oppakken!

Zet de ticket dan even op je naam, er zit al een js bestand bij inmiddels :)
